version: "3.7"

services:
  app:
    build:
      context: ./docker/app
    container_name: ${COMPOSE_PROJECT_NAME}_app
    hostname: '[${COMPOSE_PROJECT_NAME}_app]'
    ports:
      - ${HTTP_PORT:-80}:80
    volumes:
      - ${SOURCE_ROOT}:/var/www/html
    depends_on:
      - database
    restart: unless-stopped
    logging:
      options:
        max-file: "5"
        max-size: "10m"

  database:
    image: docker.io/bitnami/mariadb:10.3
    container_name: ${COMPOSE_PROJECT_NAME}_database
    hostname: '[${COMPOSE_PROJECT_NAME}_database]'
    environment:
      - MARIADB_USER=future-presents
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=future-presents
    restart: unless-stopped
    logging:
      options:
        max-file: "5"
        max-size: "10m"

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
