version: "3.7"

services:
  app:
    build:
      context: ./docker/app
    container_name: ${COMPOSE_PROJECT_NAME}_app
    hostname: '[${COMPOSE_PROJECT_NAME}_app]'
    ports:
      - ${API_PORT:-80}:80
    volumes:
      - ${SOURCE_ROOT}:/var/www/html
    depends_on:
      - database
    restart: unless-stopped
    logging:
      options:
        max-file: "5"
        max-size: "10m"

  database:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_database
    hostname: '[${COMPOSE_PROJECT_NAME}_database]'
    volumes:
      - ${DATABASE_ROOT}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      TZ: "Europe/Paris"
    ports:
      - ${DB_PORT:-3306}:3306
    restart: unless-stopped
    logging:
      options:
        max-file: "5"
        max-size: "10m"

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
