# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    exception:
        enabled: true
    view:
        view_response_listener:  'force'
        formats:
          json: true
    body_listener:
        enabled: true
        decoders:
            json:   fos_rest.decoder.json
