gesdinet_jwt_refresh_token:
  ttl: 2592000
  ttl_update: true
  cookie:
    enabled: true
    same_site: lax               # default value
    path: /                      # default value
    domain: null                 # default value
    http_only: true              # default value
    secure: false                # default value
    remove_token_from_body: true # default value
