lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: id  # key under which the user identity will be stored in the token payload
    token_ttl: 3600

    token_extractors:
        authorization_header:
            enabled: false
        cookie:
            enabled: true
            name: BEARER
    set_cookies:
        BEARER:
            lifetime: null
            samesite: lax
            path: /
            domain: null
            secure: false
            httpOnly: true
    remove_token_from_body_when_cookies_used: true
