controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

login:
    path: /login

gesdinet_jwt_refresh_token:
    path: /refresh-token
